
spring:
  # Db
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: postgres
    password: makara1234
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

## Server Configuration
#server:
#  port: 8080
#  # Session Settings (Optional)
#  servlet:
#    session:
#      timeout: 30m
#    # maximum-sessions: 1
#    # max-sessions-prevents-login: true

## Logging Configuration
#logging:
#  level:
#    root: INFO
#    org.hibernate.sql: debug
#    # Shows parameter binding values
#    org.hibernate.type.descriptor.sql: info